language: node_js

node_js:
  - "0.12"

before_script:
  - npm install --quiet -g grunt-cli karma bower phantomjs
  - npm install
  - bower install

script: grunt

after_success:
  - cat ./coverage/*/lcov.info | ./node_modules/coveralls/bin/coveralls.js
